### ISSUE TITLE
v2.6.0

### ISSUE THREAD

**Issue by adamgoose** [dlord/ftb-infinity-docker#1]
Would it be possible to get a tagged image for 2.6.0?

Thanks!

**Comment by dlord** [comment]
Sure, I can do this within the day.

**Comment by dlord** [comment]
Image for 2.6.0 is already being built in docker hub. It'll be available in a few minutes.

Closing this.

**Comment by dlord** [comment]
@adamgoose before I forget, make sure to read the updated docs of the base image (https://hub.docker.com/r/dlord/minecraft/). I've updated the docs to reflect the changes to the docker image.
